version: "3.8"

services:
  postgres_app:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: perfume
    ports:
      - '5432:5432'
    networks:
      - arquitectura

  app:
    build: .
    depends_on:
      - postgres_app
    ports:
      - '8080:8080'
    environment:
       SPRING_PROFILES_ACTIVE: docker
    networks:
      - arquitectura

networks:
  arquitectura:
    driver: bridge
