version: "3.8"

services:
  postgres_app:
    build: 
      context: .
      dockerfile: Dockerfile_postgre
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: perfume
    ports:
      - '5432:5432'
    networks:
      - arquitectura

  back:
    build: .
    depends_on:
      - postgres_app
    ports:
      - '8080:8080'
    environment:
       SPRING_PROFILES_ACTIVE: docker
    networks:
      - arquitectura  
      
  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - postgres_app
      - back
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - arquitectura

networks:
  arquitectura:
    driver: bridge
